const U='https://ihnfetkbsrlsodabxsam.supabase.co',K='sb_publishable_Zz7PZEK_yAZFCcm6DqJ5BA_vsoXCjks';
const $=id=>document.getElementById(id);
const state={question:'Which should I choose?',context:'',options:{A:{name:'Option A',image:null,file:null,link:'',price:'',edit:{zoom:1,x:0,y:0,rotation:0}},B:{name:'Option B',image:null,file:null,link:'',price:'',edit:{zoom:1,x:0,y:0,rotation:0}}},votes:{A:0,B:0},shareToken:null,aiPick:null};
function show(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(id).classList.add('active');if(id==='resultsView')results();scrollTo(0,0)}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>show(b.dataset.go));
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function safeUrl(s){try{const u=new URL(s);return /^https?:$/.test(u.protocol)?u.href:''}catch{return''}}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),3200)}
function transform(k){const e=state.options[k].edit;return `translate(${e.x}%,${e.y}%) scale(${e.zoom}) rotate(${e.rotation}deg)`}
function paint(k){const im=$(`preview${k}`);if(im)im.style.transform=transform(k)}
function autoFrame(k){state.options[k].edit={zoom:1,x:0,y:0,rotation:0};paint(k)}
function revealImage(k,src){const o=state.options[k];o.image=src;const im=$(`preview${k}`);im.onload=()=>autoFrame(k);im.src=src;im.classList.remove('hidden');$(`sourceActions${k}`).classList.add('source-actions-over-image');$(`edit${k}`).classList.remove('hidden')}
for(const k of ['A','B']){document.querySelector(`[data-upload="${k}"]`).onclick=()=>$( `file${k}`).click();$(`file${k}`).onchange=e=>{const f=e.target.files[0];if(!f)return;state.options[k].file=f;revealImage(k,URL.createObjectURL(f))}}
let editingKey=null;
function editorPaint(){if(!editingKey)return;const r=state.options[editingKey].edit;$('editorPreview').style.transform=`translate(${r.x}%,${r.y}%) scale(${r.zoom}) rotate(${r.rotation}deg)`}
function openEditor(k){const o=state.options[k];if(!o.image)return;editingKey=k;$('editorHeading').textContent=`Edit Option ${k}`;$('editorPreview').src=o.image;$('editZoom').value=o.edit.zoom;$('editX').value=o.edit.y;$('editY').value=o.edit.y;$('photoEditor').classList.remove('hidden');editorPaint()}
document.querySelectorAll('[data-edit-photo]').forEach(b=>b.onclick=()=>openEditor(b.dataset.editPhoto));
$('editZoom').oninput=e=>{state.options[editingKey].edit.zoom=+e.target.value;editorPaint()};$('editX').oninput=e=>{state.options[editingKey].edit.x=+e.target.value;editorPaint()};$('editY').oninput=e=>{state.options[editingKey].edit.y=+e.target.value;editorPaint()};$('editRotate').onclick=()=>{state.options[editingKey].edit.rotation=(state.options[editingKey].edit.rotation+90)%360;editorPaint()};$('editReset').onclick=()=>{state.options[editingKey].edit={zoom:1,x:0,y:0,rotation:0};$('editZoom').value=1;$('editX').value=0;$('editY').value=0;editorPaint()};$('applyEdit').onclick=()=>{paint(editingKey);$('photoEditor').classList.add('hidden');editingKey=null};$('closeEditor').onclick=()=>{$('photoEditor').classList.add('hidden');if(editingKey)paint(editingKey);editingKey=null};
function sync(){state.question=$('questionInput').value.trim()||'Which should I choose?';state.context=$('contextInput').value.trim();for(const k of ['A','B']){state.options[k].name=$(`option${k}Name`).value.trim()||`Option ${k}`;state.options[k].link=$(`option${k}Link`).value.trim();state.options[k].price=$(`option${k}Price`).value.trim()}}
function card(k,vote=false){const o=state.options[k],im=o.image?`<div class="option-image"><img src="${o.image}" style="transform:${transform(k)}"></div>`:`<div class="option-image">No photo</div>`;const raw=safeUrl(o.link),dest=raw?(typeof outboundUrl==='function'?outboundUrl(raw):raw):'',m=raw&&typeof merchantFor==='function'?merchantFor(raw):'other',ln=dest?`<a class="product-link" data-merchant="${m}" target="_blank" rel="noopener sponsored" href="${dest}">View item ↗</a>`:'';return `<div class="${vote?'vote-card':'compare-card'}"><div class="option-badge">${k}</div>${im}<h3>${esc(o.name)}</h3>${o.price?`<div class="price-line">${esc(o.price)}</div>`:''}${ln}${vote?`<button class="primary wide vote-btn" data-vote="${k}">Vote ${k}</button>`:''}</div>`}
function choose(){const A=state.options.A,B=state.options.B;let a=0,b=0;if(A.price&&B.price){const pa=parseFloat(A.price.replace(/[^0-9.]/g,'')),pb=parseFloat(B.price.replace(/[^0-9.]/g,''));if(pa<pb)a++;if(pb<pa)b++}state.aiPick=a===b?(Math.random()<.5?'A':'B'):(a>b?'A':'B');return state.aiPick}
$('decideBtn').onclick=()=>{sync();const p=choose();$('verdictQuestion').textContent=state.question;$('verdictLetter').textContent=p;$('verdictWinner').textContent=state.options[p].name;$('verdictReason').textContent='Based on the information provided, this is the stronger pick right now. Friends can vote too.';$('verdictOptions').innerHTML=card('A')+card('B');show('verdictView')};
async function rpc(name,body){const r=await fetch(`${U}/rest/v1/rpc/${name}`,{method:'POST',headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error(`${name}: ${await r.text()}`);return r.json()}
async function upload(k){const o=state.options[k];if(!o.file)return o.image&&/^https?:/.test(o.image)?o.image:null;const ext=(o.file.name.split('.').pop()||'jpg').toLowerCase(),name=`${crypto.randomUUID()}-${k}.${ext}`;const r=await fetch(`${U}/storage/v1/object/tiebreak-images/${name}`,{method:'POST',headers:{apikey:K,Authorization:`Bearer ${K}`,'Content-Type':o.file.type||'application/octet-stream'},body:o.file});if(!r.ok)throw Error(`Option ${k} image upload failed: ${await r.text()}`);return `${U}/storage/v1/object/public/tiebreak-images/${name}`}
function token(){const a=crypto.getRandomValues(new Uint8Array(24));return[...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function publish(){if(state.shareToken)return state.shareToken;toast('Publishing…');const ia=await upload('A'),ib=await upload('B'),ct=token(),opt=(k,img)=>{const o=state.options[k];return{name:o.name,image_url:img,product_url:safeUrl(o.link)||null,price_text:o.price||null,source_text:null,image_zoom:o.edit.zoom,image_x:o.edit.x,image_y:o.edit.y,image_rotation:o.edit.rotation}},d=await rpc('create_tiebreak',{p_creator_token:ct,p_question:state.question,p_context:state.context||null,p_option_a:opt('A',ia),p_option_b:opt('B',ib)}),row=Array.isArray(d)?d[0]:d;if(!row?.share_token)throw Error('No share token returned');state.shareToken=row.share_token;localStorage.setItem(`creator_${row.share_token}`,ct);return row.share_token}
function shareUrl(){return `${location.origin}/d/${state.shareToken}`}
function shareImageUrl(){return `${location.origin}/api/og?token=${encodeURIComponent(state.shareToken)}`}
async function copyVoteLink(silent=false){const u=shareUrl();try{await navigator.clipboard.writeText(u);if(!silent)toast('Voting link copied!');return true}catch{if(!silent)toast('Copy this link: '+u);return false}}
async function nativeShare(){const u=shareUrl();if(navigator.share){try{await navigator.share({url:u});return}catch(e){if(e.name==='AbortError')return}}await copyVoteLink()}
async function shareCardFile(){const r=await fetch(shareImageUrl(),{cache:'no-store'});if(!r.ok)throw Error('Share card unavailable');const blob=await r.blob();return new File([blob],'tiebreak.png',{type:'image/png'})}
async function nativeShareCard(){try{const file=await shareCardFile();const data={files:[file]};if(navigator.share&&(!navigator.canShare||navigator.canShare(data))){await navigator.share(data);return true}}catch(e){if(e?.name==='AbortError')return true;console.warn('Card share fallback',e)}return false}
function openShareHub(){$('shareCardImage').src=shareImageUrl();$('shareHub').classList.remove('hidden')}
function closeShareHub(){$('shareHub').classList.add('hidden')}
async function shareInstagram(){const copied=await copyVoteLink(true);toast(copied?'Voting link copied. Choose Instagram → Story, then add a Link sticker and paste.':'Choose Instagram → Story. Add a Link sticker with your Tiebreak voting link.');setTimeout(()=>nativeShareCard().then(ok=>{if(!ok)nativeShare()}),700)}
async function shareSocial(kind){if(kind==='instagram'){await shareInstagram();return}if(kind==='facebook'){await copyVoteLink();toast('Voting link copied — share the card, then paste the link into your Facebook post');const ok=await nativeShareCard();if(!ok)await nativeShare();return}await copyVoteLink();toast(`Voting link copied — choose ${kind[0].toUpperCase()+kind.slice(1)} in the share sheet`);setTimeout(()=>nativeShareCard().then(ok=>{if(!ok)nativeShare()}),350)}
$('closeShareHub').onclick=closeShareHub;$('shareMore').onclick=nativeShare;$('copyVoteLink').onclick=copyVoteLink;$('shareFacebook').onclick=()=>shareSocial('facebook');$('shareInstagram').onclick=()=>shareSocial('instagram');$('shareTikTok').onclick=()=>shareSocial('tiktok');$('shareSnapchat').onclick=()=>shareSocial('snapchat');
function voteStorageKey(){return state.shareToken?`vote_${state.shareToken}`:null}
function currentVote(){const key=voteStorageKey();return key?localStorage.getItem(key):null}
function setVoteState(k){const confirmation=$('voteConfirmation'),change=$('changeVoteBtn');if(k){confirmation.textContent=`Your vote: Option ${k}.`;confirmation.classList.remove('hidden');document.querySelectorAll('.vote-btn').forEach(b=>b.disabled=true);if(change)change.classList.remove('hidden')}else{confirmation.classList.add('hidden');document.querySelectorAll('.vote-btn').forEach(b=>b.disabled=false);if(change)change.classList.add('hidden')}}
function addViralActions(){const panel=$('voteView').querySelector('.panel'),resultsBtn=panel.querySelector('[data-go="resultsView"]');if(!$('changeVoteBtn')){const change=document.createElement('button');change.id='changeVoteBtn';change.className='secondary wide hidden';change.textContent='Change my vote';change.onclick=()=>{setVoteState(null);toast('Choose your new answer')};resultsBtn.before(change)}if(!$('voteShareBtn')){const share=document.createElement('button');share.id='voteShareBtn';share.className='secondary wide';share.textContent='Share this Tiebreak';share.onclick=openShareHub;panel.appendChild(share)}if(!$('makeOwnBtn')){const own=document.createElement('button');own.id='makeOwnBtn';own.className='primary wide';own.textContent='Create your own Tiebreak →';own.onclick=()=>location.href='/';panel.appendChild(own)}}
function votePage(){$('voteQuestion').textContent=state.question;$('voteOptions').innerHTML=card('A',true)+card('B',true);document.querySelectorAll('.vote-btn').forEach(b=>b.onclick=()=>cast(b.dataset.vote));addViralActions();setVoteState(currentVote());show('voteView')}
$('shareBtn').onclick=async()=>{try{await publish();openShareHub()}catch(e){console.error(e);toast(`Could not publish: ${String(e.message||e).slice(0,90)}`)}};$('creatorVoteBtn').onclick=async()=>{try{await publish();votePage()}catch(e){console.error(e);toast(`Could not publish: ${String(e.message||e).slice(0,90)}`)}};
async function cast(k){try{let fp=localStorage.getItem('voter')||crypto.randomUUID();localStorage.setItem('voter',fp);const prior=currentVote();const v=await rpc('cast_vote',{p_share_token:state.shareToken,p_option_key:k,p_voter_fingerprint:fp});state.votes={A:+v.A||0,B:+v.B||0};const key=voteStorageKey();if(key)localStorage.setItem(key,k);setVoteState(k);toast(prior&&prior!==k?'Vote changed!':'Vote counted')}catch(e){console.error(e);toast('Vote failed')}}
async function load(t){const d=await rpc('get_tiebreak',{p_share_token:t});if(!d)throw Error('Not found');state.shareToken=d.share_token;state.question=d.question;state.context=d.context||'';state.votes={A:+d.votes.A||0,B:+d.votes.B||0};state.aiPick=d.ai_pick;for(const o of d.options){state.options[o.option_key]={name:o.name,image:o.image_url,file:null,link:o.product_url||'',price:o.price_text||'',edit:{zoom:+(o.image_zoom||1),x:+(o.image_x||0),y:+(o.image_y||0),rotation:+(o.image_rotation||0)}}}votePage()}
async function results(){if(state.shareToken)try{const d=await rpc('get_tiebreak',{p_share_token:state.shareToken});state.votes={A:+d.votes.A||0,B:+d.votes.B||0}}catch{}const n=state.votes.A+state.votes.B,a=n?Math.round(state.votes.A/n*100):0,b=n?100-a:0,w=!n?'—':state.votes.A===state.votes.B?'Tie':state.votes.A>state.votes.B?'A':'B';$('resultsQuestion').textContent=state.question;$('resultsWinner').textContent=w;$('resultsWinnerName').textContent=w==='Tie'?'It’s a tie':w==='—'?'No votes yet':state.options[w].name;$('aiPickResult').textContent=state.aiPick||'—';$('peoplePickResult').textContent=w;$('totalVotes').textContent=n;$('pctA').textContent=a+'%';$('pctB').textContent=b+'%';$('barA').style.width=a+'%';$('barB').style.width=b+'%'}
$('resetBtn').onclick=()=>location.href='/';const m=location.pathname.match(/^\/d\/([a-f0-9]+)/i);if(m)load(m[1]).catch(()=>{toast('Tiebreak not found');show('homeView')});